version: '3'
services:
  crane-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "crane"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "crane"
#      MYSQL_TCP_PORT: 3307
    ports:
#      - "127.0.0.1:3307:3306"
      - "3306:3306"
    command: mysqld --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    volumes:
      - "./docker/init/mysql/:/docker-entrypoint-initdb.d"
    container_name: crane-mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
#  crane-app:
#    container_name: crane-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: crane
#    working_dir: /crane-app
#    ports:
#      - 7070:8080
#    depends_on:
#      crane-mysql:
#        condition: service_healthy