apiVersion: v1
kind: Service
metadata:
  name: crane-http
  labels:
    app: crane
spec:
  type: LoadBalancer
  selector:
    app: crane
  ports:
    - name: http
      port: 80
      targetPort: 8080
